//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_and_login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register1
    {
        public int studentid { get; set; }
        public string studntfname { get; set; }
        public string studentlname { get; set; }
        public string studentdept { get; set; }
        public Nullable<long> stumobilenumber { get; set; }
    }
}
